name: hackathonplugin
version: '${project.version}'
main: polepi.hackathonpl.Hackathonplugin
api-version: '1.19'
authors: [Polepi, NotEther, Sam]
description: Plugin to be submitted for the EpiTech hackathon
